//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRuuviTag {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NRuuviTag.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Error_PublisherIsAlreadyRunning {
            get {
                return ResourceManager.GetString("Error_PublisherIsAlreadyRunning", resourceCulture);
            }
        }
        
        internal static string Error_PublishError {
            get {
                return ResourceManager.GetString("Error_PublishError", resourceCulture);
            }
        }
        
        internal static string Error_UnexpectedDataFormat {
            get {
                return ResourceManager.GetString("Error_UnexpectedDataFormat", resourceCulture);
            }
        }
        
        internal static string Error_UnexpectedPayloadLength {
            get {
                return ResourceManager.GetString("Error_UnexpectedPayloadLength", resourceCulture);
            }
        }
        
        internal static string Error_UnknownDataFormat {
            get {
                return ResourceManager.GetString("Error_UnknownDataFormat", resourceCulture);
            }
        }
        
        internal static string Error_IncorrectMacAddressSequenceLength {
            get {
                return ResourceManager.GetString("Error_IncorrectMacAddressSequenceLength", resourceCulture);
            }
        }
    }
}
