//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRuuviTag.AzureEventHubs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NRuuviTag.AzureEventHubs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch with {0} items published to event hub..
        /// </summary>
        internal static string LogMessage_EventHubBatchPublished {
            get {
                return ResourceManager.GetString("LogMessage_EventHubBatchPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting event hub client..
        /// </summary>
        internal static string LogMessage_EventHubClientStarting {
            get {
                return ResourceManager.GetString("LogMessage_EventHubClientStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event hub client stopped..
        /// </summary>
        internal static string LogMessage_EventHubClientStopped {
            get {
                return ResourceManager.GetString("LogMessage_EventHubClientStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event hub publish error..
        /// </summary>
        internal static string LogMessage_EventHubPublishError {
            get {
                return ResourceManager.GetString("LogMessage_EventHubPublishError", resourceCulture);
            }
        }
    }
}
